### ISSUE TITLE
NBT Reading Test fails

### ISSUE THREAD

**Issue by nickrobson** [PocketServer/PocketServer#81]
See http://ci.nickr.xyz/job/PocketServer/lastBuild/org.pocketserver$pocketserver-server/testReport/org.pocketserver.nbt/TestNbtReading/testReading/

It's been failing for the past 14 builds.

**Comment by Fireflies** [comment]
We're aware. Updated the code to represent the proper structure last night, though there is some work to be done on reading tags from lists.
